name: Update workshop packages
on:
  push:
    branches:
      - main

jobs:
  update_packages:
    name: Update
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Azure Function zip
      run:  cd src/HoL.Redis.Func.Watcher && zip -r ../../HoL.Redis.Func.Watcher.zip .

    - name: API zip
      run:  cd src/HoL.Redis.Api && zip -r ../../HoL.Redis.Api.zip .

    - name: APIM Policies zip
      run:  cd src/HoL.Apim.Policies && zip -r ../../HoL.Apim.Policies.zip .

    - name: Infrastructure As Code zip
      run:  cd terraform && zip -r ../infrastructure-terraform.zip .

    - name: Update release
      uses: ncipollo/release-action@v1.12.0
      with:
        name: Workshop packages
        tag: latest
        artifacts: "*.zip"
        allowUpdates: true